name: Build & Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.ARN}}
          aws-region: ${{ secrets.REGION}}
      - name: Remove Old Version
        run: |
          aws s3 rm s3://${{ secrets.BUCKET_NAME }}/${{ secrets.DIRECTORY }} --recursive
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.BUCKET_NAME }}/${{ secrets.DIRECTORY }}
